### ISSUE TITLE
Cloud Pack Bearer Token

### ISSUE THREAD

**Issue by sarahbacha** [watson-developer-cloud/spring-boot-starter#18]
Is there a way to auto wire with bearer token as authentication?
Currently trying 
watson.discovery.apiKey=<Bearer Token>
But from the source code I can tell this is using a Basic Authentication

**Comment by kevinkowa** [comment]
I will look at this! Thank you for bringing this up!

**Comment by kevinkowa** [comment]
This is now available in the latest release! 🎉
