### ISSUE TITLE
[Watson-Discovery]Bean of type 'com.ibm.watson.discovery.v2.Discovery' that could not be found.

### ISSUE THREAD

**Issue by munish-usit** [watson-developer-cloud/spring-boot-starter#22]
Issue - Bean of type 'com.ibm.watson.discovery.v2.Discovery'  could not be found.
JDK version - 11

Steps to reproduce
Autowired Discovery

1. @Autowired
	Discovery discovery;	

2. pom.xml

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
  			<groupId>com.ibm.watson.developer_cloud</groupId>
  			<artifactId>watson-spring-boot-starter</artifactId>
  			<version>2.1.4</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

3. Packages used in code
import com.ibm.cloud.sdk.core.http.Response;
import com.ibm.watson.discovery.v2.Discovery;
import com.ibm.watson.discovery.v2.model.QueryOptions;
import com.ibm.watson.discovery.v2.model.QueryResponse;

I am not able to find answers on other forums like stackoverflow. May be I am missing some dependencies in pom.xml.

Stack Trace
***************************
APPLICATION FAILED TO START
***************************

Description:

Field discovery in com.xyz.search.controller.SearchController required a bean of type 'com.ibm.watson.discovery.v2.Discovery' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.ibm.watson.discovery.v2.Discovery' in your configuration.

**Comment by kevinkowa** [comment]
@munish-usit did you set your credentials in the application.properties file?
```
Add your Watson service(s) credentials and version info to your application properties file. 
The standard location for application properties is the src/main/resources/application.properties
```
for example
```
watson.discovery-v2.apiKey={APIKEY}
watson.discovery-v2.versionDate=2017-12-15
```

**Comment by munish-usit** [comment]
This issue is no longer coming and can be closed now.
