### ISSUE TITLE
Rename to comply with Spring Boot's naming guidelines

### ISSUE THREAD

**Issue by wilkinsona** [watson-developer-cloud/spring-boot-starter#4]
The Spring Boot documentation [requests](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) that third-party starters be named `*-spring-boot-starter`. The current name of this module, `spring-boot-starter`, is particularly bad as it clashes with one of Spring Boot's own modules. `watson-spring-boot-starter` would, IMO, be a better name. Also, please note that the naming scheme that's recommended in the reference documentation is also a [requirement](https://github.com/spring-io/initializr/wiki/Guidelines-for-3rd-Party-Starters) for inclusion on [start.spring.io](https://start.spring.io).

**Comment by germanattanasio** [comment]
@wilkinsona we will do the change so that the dependency in maven is `watson-spring-boot-starter`. This repository won't be renamed though
