### ISSUE TITLE
Please update <service> name to comply with Spring Boot 2 rules for externalized configuration

### ISSUE THREAD

**Issue by ka4ok85** [watson-developer-cloud/spring-boot-starter#7]
Please see [https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#externalized-configuration](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#externalized-configuration):

> All prefixes must be in kebab-case format (lower-case, hyphen separated), acme.myProject or acme.my_project are invalid - you must use acme.my-project here

Steps to reproduce:
1. Spring Boot version: 2.0.0.M7
2. Watson-spring-boot-starter version: 0.0.2
3. During startup following error returned:

`Configuration property name 'watson.language_translator' is not valid:`

`Invalid characters: '_'
    Bean: com.ibm.watson.developer_cloud.spring.boot.WatsonAutoConfiguration
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter`

`Modify 'watson.language_translator' so that it conforms to the canonical names requirements.`

**Comment by germanattanasio** [comment]
@mkistler ☝️

**Comment by ka4ok85** [comment]
Resolved in #8
